[CA-9] - Deploy

diff --git a/.github/workflows/on-push-tags.yml b/.github/workflows/on-push-tags.yml
--- a/.github/workflows/on-push-tags.yml
+++ b/.github/workflows/on-push-tags.yml
@@ -25,24 +25,75 @@ jobs:
           echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
           echo "==== Deploy to $ENVIRONMENT"
 
-      - name: Replace Deployment Image Version
+      - name: Check Deployment Image Version
         run: |
-          yq -i '.spec.template.spec.containers[0].image |=
-            sub("cart-api.*", "cart-api.${{ github.ref_name }}")' .k8s/${{ env.ENVIRONMENT }}/deployment.yml
+          IMAGE_VERSION=$(cat .k8s/staging/deployment.yml | yq -r .spec.template.spec.containers[0].image | sed "s/.*.:[a-z-]*.//")
 
-          git config user.name RempelOliveira
-          git config user.email rempel.oliveira@gmail.com
-
-          git checkout -b ${{ github.event.base_ref }}
-          git add .
-
-          if [[ $(git status --porcelain | wc -l) == 1 ]]; then
-            git push origin :refs/tags/${{ github.ref_name }}
-
-            git tag -fa ${{ github.ref_name }} \
-              -m "Replaced Deployment Image Version to ${{ github.ref_name }}"
-
-            git push origin ${{ github.ref_name }} --tags
-          else
-            echo "==== No changes to commit"
+          if [[ IMAGE_VERSION != ${{ github.ref_name }} ]]; then
+            echo "==== Error: The image version is different from tag"
+            exit 1
           fi
+
+      - id: cache
+        name: Packages Cache
+        uses: actions/cache@v3
+        with:
+          key: cache-packages-e720e97a-38d5-498d-be12-6d077d9f5d43
+          path: |
+            /usr/local/bin/yq
+            /usr/local/bin/argocd
+          restore-keys: |
+            cache-packages-e720e97a-38d5-498d-be12-6d077d9f5d43
+
+      - name: SetUp Yq
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
+          chmod +x /usr/local/bin/yq
+
+      - name: SetUp ArgoCd
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
+
+          rm argocd-linux-amd64
+
+      - name: SetUp Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and Push Docker Image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          push: true
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          tags: rempeloliveira/public:cart-api.${{ github.ref_name }}
+
+      - name: Sync ArgoCd Application
+        run: |
+          argocd login ${{ secrets.ARGOCD_SERVER }} \
+            --username ${{ secrets.ARGOCD_USERNAME }} \
+            --password ${{ secrets.ARGOCD_PASSWORD }} \
+            --grpc-web
+
+          argocd app create cart-api${{ env.ENVIRONMENT == 'staging' && '-staging' || '' }} \
+            --repo https://github.com/RempelOliveira/LojaIntegrada.Backend.git \
+            --path .k8s/${{ env.ENVIRONMENT }} \
+            --revision ${{ github.ref_name }} \
+            --dest-server https://kubernetes.default.svc \
+            --dest-namespace ${{ env.ENVIRONMENT }}-apps \
+            --server ${{ secrets.ARGOCD_SERVER }} \
+            --grpc-web \
+            --upsert
+
+          argocd app sync cart-api${{ env.ENVIRONMENT == 'staging' && '-staging' || '' }} \
+            --server ${{ secrets.ARGOCD_SERVER }} \
+            --grpc-web
